// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AggregatedCategory struct {
	Category *Category `json:"category"`
	Count    *int      `json:"count,omitempty"`
}

type Category struct {
	Subcategory string `json:"subcategory"`
}

type Data struct {
	ID         string              `json:"id"`
	Categories *Category           `json:"categories"`
	Title      *MultiLanguageTitle `json:"title"`
	Type       string              `json:"type"`
	Posted     float64             `json:"posted"`
}

type DataPage struct {
	Data          []*Data `json:"data"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

type MultiLanguageTitle struct {
	Ro string `json:"ro"`
	Ru string `json:"ru"`
}

type Query struct {
}
